"""Pydantic schemas for Trading Consultation Subsystem."""

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from uuid import uuid4
from pydantic import BaseModel, Field


class TradingTelemetry(BaseModel):
    """Real-time performance telemetry emitted by the trading bot."""
    equity: float = Field(description="Current account equity in USDT")
    unrealized_pnl: float = Field(description="Current floating PnL of open positions")
    realized_pnl: float = Field(description="Cumulative realized profit/loss")
    win_rate: float = Field(ge=0.0, le=1.0, description="Historical win rate fraction between 0.0 and 1.0")
    profit_factor: float = Field(description="Gross profits divided by gross losses")
    max_drawdown_pct: float = Field(description="Peak-to-trough drawdown percentage")
    consecutive_losses: int = Field(ge=0, description="Current consecutive losing trade count")
    total_trades: int = Field(ge=0, description="Total count of completed trades")
    sharpe_ratio: Optional[float] = Field(default=None, description="Annualized or period Sharpe ratio")


class StrategyPerformance(BaseModel):
    """Performance breakdown for an individual algorithmic trading strategy."""
    strategy_name: str = Field(description="Identifier or name of the strategy (e.g. Supertrend, EMA_Cross)")
    trade_count: int = Field(ge=0, description="Trades executed by this specific strategy")
    win_rate: float = Field(ge=0.0, le=1.0, description="Strategy win rate fraction (0.0 - 1.0)")
    profit_factor: float = Field(description="Strategy profit factor")
    net_pnl: float = Field(description="Net realized PnL generated by this strategy")
    avg_win: float = Field(description="Average profit on winning trades")
    avg_loss: float = Field(description="Average loss on losing trades")
    consecutive_losses: int = Field(ge=0, description="Current consecutive losses for this strategy")


class TradingConsultRequest(BaseModel):
    """Advisory request submitted by an autonomous trading bot instance."""
    bot_id: str = Field(description="Unique identifier of the consulting bot instance")
    trading_mode: Literal["PAPER", "TESTNET"] = Field(description="Operational mode (only non-live modes allowed)")
    experiment_id: Optional[str] = Field(default=None, description="Optional experiment tracking identifier")
    telemetry: TradingTelemetry = Field(description="High-level account and performance telemetry")
    strategy_performance: List[StrategyPerformance] = Field(default_factory=list, description="Per-strategy performance telemetry")
    current_parameters: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Current live parameters: strategy_name -> parameter_name -> current_value"
    )
    regime_data: Optional[Dict[str, Any]] = Field(default=None, description="Market regime indicators, volatility, trend state")
    recent_trades: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Last 10-20 closed trades with entry, exit, pnl, side, duration"
    )
    consultation_reason: Literal["SCHEDULED", "DRAWDOWN_EVENT", "LOSS_STREAK", "MANUAL"] = Field(
        description="Trigger context for requesting advisory consultation"
    )


class ParameterChange(BaseModel):
    """Bounded parameter calibration recommendation."""
    strategy: str = Field(description="Target strategy name")
    parameter: str = Field(description="Parameter key name (e.g. stop_loss_pct, atr_multiplier)")
    current_value: Any = Field(description="Current value before recommendation")
    recommended_value: Any = Field(description="New recommended value proposed by consultation")
    change_pct: float = Field(description="Computed percentage change relative to current value")
    rationale: str = Field(description="Evidence-based reasoning derived from multi-agent debate")


class AIUniverseDecision(BaseModel):
    """Final structured advisory decision produced by AI Universe."""
    decision_id: str = Field(default_factory=lambda: str(uuid4()), description="Unique UUID for this advisory decision")
    timestamp: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="ISO 8601 creation timestamp"
    )
    status: Literal["RECOMMENDATION", "NO_CHANGE", "INSUFFICIENT_DATA"] = Field(
        description="Advisory status outcome"
    )
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence score in the recommendation (0.0 to 1.0)")
    parameter_changes: List[ParameterChange] = Field(
        default_factory=list,
        description="Bounded parameter changes (maximum 2, prefer 1)"
    )
    risk_assessment: str = Field(description="Narrative assessment of current drawdown, risk, and downside exposure")
    regime_analysis: str = Field(description="Interpretation of market regime data, volatility, or market trends")
    dissent_notes: str = Field(description="Critiques, dissent, or counter-risks raised by the Critic agent")
    debate_summary: str = Field(description="Condensed multi-agent deliberation trail across specialists")
    valid_until: str = Field(description="ISO 8601 expiration timestamp for this advisory decision (default 24h)")
