"""Pydantic schemas for Trading Consultation Subsystem, A/B Testing, and Testnet Support."""

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from uuid import uuid4
from pydantic import BaseModel, Field


class TradingTelemetry(BaseModel):
    """Real-time performance telemetry emitted by the trading bot."""
    equity: float = Field(description="Current account equity in USDT")
    unrealized_pnl: float = Field(description="Current floating PnL of open positions")
    realized_pnl: float = Field(description="Cumulative realized profit/loss")
    win_rate: float = Field(ge=0.0, le=1.0, description="Historical win rate fraction between 0.0 and 1.0")
    profit_factor: float = Field(description="Gross profits divided by gross losses")
    max_drawdown_pct: float = Field(description="Peak-to-trough drawdown percentage")
    consecutive_losses: int = Field(ge=0, description="Current consecutive losing trade count")
    total_trades: int = Field(ge=0, description="Total count of completed trades")
    sharpe_ratio: Optional[float] = Field(default=None, description="Annualized or period Sharpe ratio")


class StrategyPerformance(BaseModel):
    """Performance breakdown for an individual algorithmic trading strategy."""
    strategy_name: str = Field(description="Identifier or name of the strategy (e.g. Supertrend, EMA_Cross)")
    trade_count: int = Field(ge=0, description="Trades executed by this specific strategy")
    win_rate: float = Field(ge=0.0, le=1.0, description="Strategy win rate fraction (0.0 - 1.0)")
    profit_factor: float = Field(description="Strategy profit factor")
    net_pnl: float = Field(description="Net realized PnL generated by this strategy")
    avg_win: float = Field(description="Average profit on winning trades")
    avg_loss: float = Field(description="Average loss on losing trades")
    consecutive_losses: int = Field(ge=0, description="Current consecutive losses for this strategy")


class TestnetContext(BaseModel):
    """Testnet-specific exchange environment telemetry and live risk state."""
    testnet_equity: float = Field(description="Current testnet wallet balance / equity in USDT")
    testnet_drawdown_pct: float = Field(description="Current drawdown percentage on testnet")
    testnet_daily_loss: float = Field(default=0.0, description="Realized loss accrued during current 24h cycle")
    testnet_open_positions: int = Field(ge=0, default=0, description="Number of currently active testnet positions")
    testnet_margin_level: float = Field(default=100.0, description="Current account margin level percentage")


class TradingConsultRequest(BaseModel):
    """Advisory request submitted by an autonomous trading bot instance."""
    bot_id: str = Field(description="Unique identifier of the consulting bot instance")
    trading_mode: Literal["PAPER", "TESTNET"] = Field(description="Operational mode (only non-live modes allowed)")
    testnet_specific: Optional[TestnetContext] = Field(
        default=None,
        description="Testnet-specific live exchange state when operating on testnet"
    )
    experiment_id: Optional[str] = Field(default=None, description="Optional experiment tracking identifier")
    experiment_group: Optional[Literal["CONTROL", "TREATMENT"]] = Field(
        default=None,
        description="A/B testing arm identifier (CONTROL or TREATMENT)"
    )
    control_metrics: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Baseline metrics from the control arm for comparison analysis"
    )
    telemetry: TradingTelemetry = Field(description="High-level account and performance telemetry")
    strategy_performance: List[StrategyPerformance] = Field(default_factory=list, description="Per-strategy performance telemetry")
    current_parameters: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Current live parameters: strategy_name -> parameter_name -> current_value"
    )
    regime_data: Optional[Dict[str, Any]] = Field(default=None, description="Market regime indicators, volatility, trend state")
    recent_trades: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Last 10-20 closed trades with entry, exit, pnl, side, duration"
    )
    consultation_reason: Literal["SCHEDULED", "DRAWDOWN_EVENT", "LOSS_STREAK", "MANUAL"] = Field(
        description="Trigger context for requesting advisory consultation"
    )


class ParameterChange(BaseModel):
    """Bounded parameter calibration recommendation."""
    strategy: str = Field(description="Target strategy name")
    parameter: str = Field(description="Parameter key name (e.g. stop_loss_pct, atr_multiplier)")
    current_value: Any = Field(description="Current value before recommendation")
    recommended_value: Any = Field(description="New recommended value proposed by consultation")
    change_pct: float = Field(description="Computed percentage change relative to current value")
    rationale: str = Field(description="Evidence-based reasoning derived from multi-agent debate")


class AIUniverseDecision(BaseModel):
    """Final structured advisory decision produced by Inference."""
    decision_id: str = Field(default_factory=lambda: str(uuid4()), description="Unique UUID for this advisory decision")
    timestamp: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="ISO 8601 creation timestamp"
    )
    status: Literal["RECOMMENDATION", "NO_CHANGE", "INSUFFICIENT_DATA"] = Field(
        description="Advisory status outcome"
    )
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence score in the recommendation (0.0 to 1.0)")
    parameter_changes: List[ParameterChange] = Field(
        default_factory=list,
        description="Bounded parameter changes (maximum 2, prefer 1)"
    )
    risk_assessment: str = Field(description="Narrative assessment of current drawdown, risk, and downside exposure")
    regime_analysis: str = Field(description="Interpretation of market regime data, volatility, or market trends")
    dissent_notes: str = Field(description="Critiques, dissent, or counter-risks raised by the Critic agent")
    debate_summary: str = Field(description="Condensed multi-agent deliberation trail across specialists")
    valid_until: str = Field(description="ISO 8601 expiration timestamp for this advisory decision (default 24h)")
    # A/B testing fields
    comparison_rationale: Optional[str] = Field(
        default=None,
        description="Detailed comparative rationale explaining how this recommendation differs from or relates to the control baseline"
    )
    expected_improvement: Optional[str] = Field(
        default=None,
        description="Quantitative estimate of expected performance improvement based on historical telemetry"
    )
    treatment_status: Optional[str] = Field(
        default=None,
        description="Performance status relative to control (e.g., OUTPERFORMING_CONTROL, PARITY, UNDERPERFORMING_CONTROL)"
    )
    # Testnet-specific fields
    testnet_risk_assessment: Optional[str] = Field(
        default=None,
        description="Testnet-specific capital preservation analysis, margin level evaluation, and position sizing guidelines"
    )


# --- A/B Experiment Tracking Schemas ---

class ExperimentStartRequest(BaseModel):
    """Payload to register and launch a new A/B trading experiment."""
    experiment_id: str = Field(description="Unique experiment identifier")
    hypothesis: Optional[str] = Field(default=None, description="Hypothesis being evaluated in the experiment")
    duration_hours: float = Field(default=72.0, ge=1.0, description="Scheduled duration of the experiment in hours")
    success_metrics: List[str] = Field(
        default_factory=lambda: ["profit_factor", "win_rate", "max_drawdown_pct", "sharpe_ratio"],
        description="Key metrics used to determine the winning arm"
    )
    control_bot_id: str = Field(description="Bot instance identifier assigned to the CONTROL arm")
    treatment_bot_id: str = Field(description="Bot instance identifier assigned to the TREATMENT arm")
    initial_parameters: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Baseline parameter configuration for both arms at experiment start"
    )


class ExperimentConfigResponse(BaseModel):
    """Response returned when an A/B experiment is successfully registered."""
    experiment_id: str
    status: Literal["ACTIVE", "COMPLETED", "TERMINATED"] = "ACTIVE"
    start_time: str
    duration_hours: float
    control_config: Dict[str, Any]
    treatment_config: Dict[str, Any]
    success_metrics: List[str]
    message: str = "A/B Experiment successfully initialized."


class ExperimentStatusResponse(BaseModel):
    """Current live progress and health status of an active A/B experiment."""
    experiment_id: str
    status: Literal["ACTIVE", "COMPLETED", "TERMINATED"]
    start_time: str
    elapsed_hours: float
    duration_hours: float
    active_arms: List[str]
    consultations_count: Dict[str, int] = Field(
        default_factory=lambda: {"CONTROL": 0, "TREATMENT": 0},
        description="Count of consultations logged per arm"
    )
    latest_telemetry: Optional[Dict[str, Any]] = None


class ExperimentResultsResponse(BaseModel):
    """Aggregated results and performance analysis upon experiment completion."""
    experiment_id: str
    status: Literal["ACTIVE", "COMPLETED", "TERMINATED"]
    winner: Optional[Literal["CONTROL", "TREATMENT", "INCONCLUSIVE"]] = None
    duration_hours: float
    control_summary: Dict[str, Any]
    treatment_summary: Dict[str, Any]
    comparison_analysis: Dict[str, Any]
    conclusion: str


# --- Testnet Performance & Comparison Schemas ---

class TestnetPerformanceResponse(BaseModel):
    """Aggregated performance metrics comparing TESTNET consultations against PAPER trading."""
    total_consultations: int
    testnet_consultations: int
    paper_consultations: int
    testnet_metrics: Dict[str, Any]
    paper_metrics: Dict[str, Any]
    drawdown_distribution: Dict[str, Any]


class TestnetComparisonResponse(BaseModel):
    """Detailed side-by-side performance and strategy divergence analysis."""
    comparison_timestamp: str
    testnet_summary: Dict[str, Any]
    paper_summary: Dict[str, Any]
    strategy_divergence: List[Dict[str, Any]]
    recommendations_summary: str
